config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  
  match '/users/logout', :to => 'users#logout', :via => [:get, :post]
  get '/logout' => 'session#destroy'
  match '/panels/fault', :to => 'panels#fault', :via => [:get, :post]
  match '/panels/voltdrop', :to => 'panels#voltdrop', :via => [:get, :post]
  match '/units/appliance', :to => 'units#appliance', :via => [:get, :post]
  match '/units/hvac', :to => 'units#hvac', :via => [:get, :post]
  match '/units/load', :to => 'units#load', :via => [:get, :post]
  match '/meterbanks/load', :to => 'meterbanks#load', :via => [:get, :post]
  resources :panels
  resources :users
  resources :projects
  resources :units
  resources :meterbanks

  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@projects = Project.where(:user_id => session[:user_id])
	end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_sidebar.html.erb
    <div class = "col-sm-3 col-md-2 sidebar">
			<ul class = "nav nav-sidebar" id = "sidebar">
        <li class="active"><a href="#">Projects<span class="sr-only">(current)</span></a></li>
          <% @projects.each do |project| %>
          <li><%= link_to project.name, { controller: "projects", action: "show", id: project.id}, remote: true %>
          </li>
          <% end %>
          <%= link_to "New Project", new_project_path, class: "btn btn-md btn-default", remote: true   %> 
      </ul>

		</div>

app/views/dashboard/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="alert alert-success fade in">
      <%= flash[:notice] %>
    </div>
<% end %>


<div class = "container-fluid">
	<div class = "row">
		<div id = "sidebar">
 			<%= render partial: "dashboard/sidebar", locals: {:projects => @projects } %>
 		</div>

		<div class = "col-sm-9">
			<div class = "row" id = "dashboard">
				<% @projects.each do |project| %>
				<div class = "clearfix col-sm-5 project-dash">
					<h2><%= project.name %></h2>
					<span id = "category"> <%= "#{project.project_type}" %></span><br />
					<%= link_to "Total Panels: #{project.panels.length}", {controller: 'panels', action: 'index', project_id: project.id}, class: "btn btn-md btn-default", remote: true   %>
					<%= link_to "Units: #{project.units.length}", {controller: 'units', action: 'index', project_id: project.id}, class: "btn btn-md btn-default", remote: true   %>
					<%= link_to "Meter Banks: #{project.meterbanks.length}", {controller: 'meterbanks', action: 'index', project_id: project.id}, class: "btn btn-md btn-default", remote: true   %>
					<br /><br />
					<!--Type of Project: <%= project.project_type %> -->
				</div>
				<% end %>
			</div>
			<div id = "project-form" style="display:none;">
			</div>
		</div>
	</div>
</div>