config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  
  match '/users/logout', :to => 'users#logout', :via => [:get, :post]
  get '/logout' => 'session#destroy'
  match '/panels/fault', :to => 'panels#fault', :via => [:get, :post]
  match '/panels/voltdrop', :to => 'panels#voltdrop', :via => [:get, :post]
  match '/units/appliance', :to => 'units#appliance', :via => [:get, :post]
  match '/units/hvac', :to => 'units#hvac', :via => [:get, :post]
  match '/units/load', :to => 'units#load', :via => [:get, :post]
  match '/meterbanks/load', :to => 'meterbanks#load', :via => [:get, :post]
  resources :panels
  resources :users
  resources :projects
  resources :units
  resources :meterbanks

  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/meterbank.rb
class Meterbank < ActiveRecord::Base
	belongs_to :project
	before_save :unit, :set_total

	def unit
		Unit.where(:unit_name => self.largest_unit).first
	end

	def demand_total
		lighting = self.unit.lighting * self.unit_count
		if lighting > 120000
			(((lighting - 120000) * 0.25) + 40950 + 3000).to_i
		else 
			(((lighting - 3000) * 0.35) + 3000).to_i
		end
	end

	def appliance_total
		(((self.unit.microwave + self.unit.dishwasher +
		self.unit.disposal) * 0.75 ) * self.unit_count).to_i
	end

	def dryer_total
		((self.unit.dryer * self.unit_count) * 
		(DryerDemand.where(:count => self.unit_count).first.demand)).to_i
	end

	def hvac_total
		self.unit.hvac * self.unit_count
	end

	def set_total
		self.total_load = (self.demand_total + self.appliance_total +
		self.dryer_total + self.hvac_total)
	end
	
end

app/controllers/meterbanks_controller.rb
class MeterbanksController < ApplicationController
  respond_to :js
  before_action :get_project
  before_action :index_project

  	def index
  		@meterbanks = Meterbank.where(:project_id => @project.id)	
  	end

  	def new
  		@meterbank = Meterbank.new(:project_id => @project.id)
  		@largest_unit = Unit.where(:project_id => @project.id).map {|unit| unit.unit_name}
  	end

  	def create
  		@meterbanks = Meterbank.where(:project_id => @project.id)
	    @meterbank = Meterbank.new(meterbank_params)
	    @meterbank.save
  	end

  	def edit
  		@meterbank = Meterbank.find(params[:id])
  		@largest_unit = Unit.where(:project_id => @meterbank.project_id).map {|unit| unit.unit_name}
  	end

  	def update
  		@meterbanks = Meterbank.where(:project_id => @project.id)
  		@meterbank = Meterbank.find(params[:id])
	    @meterbank.update(meterbank_params)
  	end

  	def delete
  	end

  	def destroy
  		@meterbank = Meterbank.find(params[:id])
    	@meterbank.destroy
	    respond_to do |format|
	      format.html { redirect_to '/dashboard/index', notice: "Meterbank: #{@meterbank.bus_name} was successfully destroyed" }
	      format.json { head :no_content }
	    end
  	end

  	def load
  		@meterbanks = Meterbank.where(:project_id => @project.id)
  	end

  	def meterbank_params
      params.require(:meterbank).permit(:bus_name, :unit_count, :largest_unit, :dryer_demand, 
      	:load_demand, :lighting, :appliance, :dryer_total, :hvac_total, :total_load, :project_id)
   	end
	
end

app/helpers/meterbanks_helper.rb
module MeterbanksHelper
end

app/views/meterbanks/_form.html.erb
<%= form_for @meterbank, remote: true do |f| %>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
  <div class="form-group">
    <%= f.label :bus_name %><br>
    <%= f.text_field :bus_name%>
  </div>
  <div class="form-group">
    <%= f.label :unit_count %><br>
    <%= f.text_field :unit_count%>
  </div>
  <div class = "form-group" >
    <%= f.label :largest_unit %><br>
    <%= f.select :largest_unit, @largest_unit, {}, {class: "form-control"} %>
  </div>

  </div>
</div>

<div class="row">
  <div class="col-sm-3">

        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @meterbank.project_id %>
          <%= f.button :Submit, name: "project_id", value: @meterbank.project_id, :class => 'btn btn-md btn-success'  %>       
          <%= link_to "Cancel", {controller: 'meterbanks', action: 'index', project_id: @meterbank.project_id }, class: "btn btn-md btn-default", remote: true   %>
          <%= link_to 'Destroy', @meterbank, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-md btn-danger" %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/meterbanks/_loadcalc.html.erb
 <div class="row">
    <div class="col-sm-7">
      <div class = "page-header"><h2>Residential Load Calculations:</h2></div>
<%= link_to "View Meter Banks", {controller: 'meterbanks', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>
  
    <% @meterbanks.each do |meter| %>
    <div id = "meter-table">
      <h4><%= "Computed Load for #{meter.unit_count}-Unit Meter Bank:" %></h4>

      <p>  <b> Computed Lighting and Small Appliance Load: </b><br/>
        <%= "Lighting and Small Appliance load for #{meter.unit_count} Units: #{number_with_delimiter(number_with_precision(meter.unit.lighting * meter.unit_count, precision: 0), :delimiter => ',')} Volt-Amperes" %><br /></p>


      <p> <b> Application of Demand Factor: </b><br />
        <%= "3,000 Volt-Amperes @ 100% = 3,000 Volt-Amperes" %><br />
        <%= "From 3001 to #{(meter.unit.lighting * meter.unit_count) < 120000 ? number_with_delimiter((meter.unit.lighting * meter.unit_count), :delimiter => ',') : '120,000'} @ 35% = #{number_with_delimiter(meter.demand_total - 3000, :delimiter => ',')} Volt-Amperes" %><br />
        <%= "Net Computed Load (#{meter.unit_count} Dwelling Units) = #{number_with_delimiter(meter.demand_total, :delimiter => ',')} Volt-Amperes" %><br />



       <p> <b>Computed Appliance Load:</b><br />
       <%= "Microwave Load for #{meter.unit_count} Units = #{number_with_delimiter(meter.unit_count * meter.unit.microwave, :delimiter => ',')} Volt-Amperes" %><br />
        <%= "Dishwasher Load for #{meter.unit_count} Units = #{number_with_delimiter(meter.unit_count * meter.unit.dishwasher, :delimiter => ',')} Volt-Amperes" %><br />
        <%= "Disposal Load for #{meter.unit_count} Units = #{number_with_delimiter(meter.unit_count * meter.unit.disposal, :delimiter => ',')} Volt-Amperes" %><br />
        <%= "Demand Load for Appliances per NEC 220-53:" %><br />
        <%= "#{number_with_delimiter((meter.unit.dishwasher + meter.unit.microwave + meter.unit.disposal) * meter.unit_count, :delimiter => ',')} Volt-Amperes @ 75% = #{number_with_delimiter(meter.appliance_total, :delimiter => ',')} Volt-Amperes" %></p>


        <p><b>Computed Dryer Load:</b><br />
        <%= "Clothes Dryer Load for #{meter.unit_count} Units = #{number_with_delimiter(meter.unit_count * meter.unit.dryer, :delimiter => ',')} Volt-Amperes" %><br />
        <%= "Demand Load for Dryers per NEC 220-54:" %><br />
        <%= "#{number_with_delimiter((meter.unit.dryer * meter.unit_count), :delimiter => ',')} Volt-Amperes at #{DryerDemand.where(:count => meter.unit_count).first.demand * 100}% = #{number_with_delimiter(meter.dryer_total, :delimiter => ',')} Volt-Amperes" %></p>


        <p><%= "HVAC Loads for #{meter.unit_count} Units @ 100% = #{number_with_delimiter(meter.hvac_total, :delimiter => ',')} Volt-Amperes" %></p>

        <p><%= "Total Computed Load (#{meter.unit_count} Dwelling Units) = " %> <b><%= "#{number_with_delimiter(meter.total_load, :delimiter => ',')} Volt-Amperes" %></b></p>

        <p><%= "Total Load at #{meter.unit_count}-Unit Meter Bank:" %><br />
          <%= "#{number_with_delimiter(meter.total_load, :delimiter => ',')} Volt-Amperes / (#{meter.unit.voltage}V * 1.732) = " %><b><%= "#{number_with_precision(meter.total_load / (meter.unit.voltage * 1.732), precision: 0)} Amperes" %></b></p>


           <hr />
           <% end %>
    </div>
    </div>
  </div>

app/views/meterbanks/_meterlist.html.erb
<div class="container">
 </div>
<%= link_to "Back to Project", project_path(@project), class: "btn btn-md btn-default", remote: true %>
 <%= link_to "New Meter Bank", {controller: 'meterbanks', action: 'new', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
  <%= link_to "Load Calculations - Conventional Method", {controller: 'meterbanks', action: 'load', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
 <div class="container">
  <div class="row">
    <div class="col-sm-11" id = "meter-table">
      <h2>Meter Bank Details</h2>
      <table class="table table-hover" style = "width: 500px;">
        <thead>
          <tr>
            <th>Meter Bank Name</th>
            <th>Number of Units</th>
            <th>Name of Largest Unit</th>
          </tr>
        </thead>

        <tbody>
          <% @meterbanks.each do |meter| %>
          <tr>
            <td><%= link_to meter.bus_name, edit_meterbank_path(meter), class: "btn btn-md btn-default", remote: true %></td>
            <td><%= meter.unit_count %></td>
            <td><%= meter.largest_unit %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
      <% if !flash[:notice].blank? %>
    <div class="alert alert-danger fade in">
      <%= flash[:notice] %>
    </div>
    <% end %>
</div>

app/views/meterbanks/create.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render "meterlist") %>");

});

app/views/meterbanks/edit.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(600);

});

app/views/meterbanks/index.js.erb
$(document).ready(function(){
	$('.project-dash').hide();
	$('#project-form').html("<%= j (render 'meterlist') %>");
	$('#project-form').show();
});

app/views/meterbanks/load.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render "loadcalc") %>");

});

app/views/meterbanks/new.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(600);

});

app/views/meterbanks/update.js.erb
$(document).ready(function(){
$('#project-form').html("<%= j (render "meterlist") %>");
});