config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  
  match '/users/logout', :to => 'users#logout', :via => [:get, :post]
  get '/logout' => 'session#destroy'
  match '/panels/fault', :to => 'panels#fault', :via => [:get, :post]
  match '/panels/voltdrop', :to => 'panels#voltdrop', :via => [:get, :post]
  match '/units/appliance', :to => 'units#appliance', :via => [:get, :post]
  match '/units/hvac', :to => 'units#hvac', :via => [:get, :post]
  match '/units/load', :to => 'units#load', :via => [:get, :post]
  match '/meterbanks/load', :to => 'meterbanks#load', :via => [:get, :post]
  resources :panels
  resources :users
  resources :projects
  resources :units
  resources :meterbanks

  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/panel.rb
class Panel < ActiveRecord::Base


before_save :set_fault, :set_c_val, :calc_final, :voltdrop
belongs_to :project
#acts_as_list :scope => :project


scope :sorted, lambda { order("panels.position ASC")}

validates_presence_of :panel_name
validates_length_of :panel_name, :maximum => 50
validates_uniqueness_of :panel_name, :scope => :project_id
validates_presence_of :wire_length
validates_presence_of :runs
validates_presence_of :wire_type
validates_presence_of :conduit_type
validates_presence_of :run_type

def set_fault
	if self.fed_from == "Transformer"
		self.init_fault = Project.find(self.project_id).init_fault
	else
		self.init_fault = Panel.where(panel_name: self.fed_from).first.final_value
	end
end

def set_c_val
	self.c_value = Cvalue.where(wire_size: self.wire_size, wire_type: self.wire_type, 
		conduit_type: self.conduit_type, runs_type: self.run_type).first.c_value
end

def calc_final
	if self.voltage != 240
		var_volt = 1.73
	else
		var_volt = 2
	end
	  self.f_value = (var_volt * self.wire_length * self.init_fault)/
      (self.runs * self.c_value * self.voltage)
      self.m_value = 1/(1+self.f_value)
      self.final_value = self.init_fault * self.m_value
end

def voltdrop
	if self.voltage != 240
		phase = 1
	else
		phase = 0
	end
	self.volt_drop = (((1/self.runs) * ((self.wire_length *
	 self.conn_ampacity) *
	 Voltdrop.where(wire_size: self.wire_size, wire_type: self.wire_type - 1, phase: phase,
	 conduit: self.conduit_type - 1).first.power_factor)) / 10000) / self.voltage
end


end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  respond_to :js
  before_action :get_project
  before_action :index_project

def index
	@panels = @project.panels.sorted
  @panels.each do |panel|
    panel.save
  end
end

def show
end

def new
    @panel = Panel.new({:project_id => @project.id})
    @panel_count = Panel.count + 1
    @panel_names = Panel.where(:project_id => @project.id).pluck(:panel_name)
    @panel_names.insert(0, "Transformer")
end

def create
	@panels = Panel.where(:project_id => @project.id)
    @panel = Panel.new(panel_params)
    @panel.save
    @panel_count = Panel.count
end
	
def fault
  @panels = Panel.where(:project_id => @project.id)
end

def voltdrop
  @panels = Panel.where(:project_id => @project.id)
end

  def edit
  	@panel = Panel.find(params[:id])
  	@panel_names = Panel.where(:project_id => @panel.project_id).pluck(:panel_name)
    @panel_names.insert(0, "Transformer")
    #For Position in Form
    @panel_count = Panel.count
  end

  def update
    @panels = Panel.where(:project_id => @project.id)
  	@panel = Panel.find(params[:id])
    @panel.update(panel_params)
  end

  def delete
  end
  # DELETE /panels/1
  # DELETE /panels/1.json
  def destroy
    @panel = Panel.find(params[:id])
    Panel.where(:fed_from => @panel.panel_name).destroy(Panel.where(:fed_from => @panel.panel_name).pluck(:id))
    flash[:notice] = "Panel '#{@panel.panel_name}' has been destroyed successfully"
    if @panel.destroy
    respond_to do |format|
      format.html { redirect_to '/dashboard/index', status: 303 }
      format.json { head :no_content }
    end
  end
  end

    def panel_params
      params.require(:panel).permit(:conn_ampacity, :temp, :wire_length, :init_fault, :runs, :voltage, :c_value, :panel_name,
        :f_value, :m_value, :final_value, :project_id, :position, :wire_type, :conduit_type, :run_type,
        :wire_size, :fed_from)
    end
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/views/panels/_details.html.erb
<div class = "page-header"><h1>Project Details</h1></div>
<div class = "container">
	<div class = "row">
							<div class = "col-md-6">
						<p>
							<strong>Name:</strong>
							<%= @project.name %>
						</p>

						<p>
							<strong>Description:</strong>
							<%= @project.description %>
						</p>


						<p>
							<strong>Fault at Transformer:</strong>
							<%= @project.init_fault %>
						</p>


						<p>
							<strong>Position:</strong>
							<%= @project.position %>
						</p>

						<p>
						<%= link_to "View Panels", {controller: 'panels', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>

						<%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-md btn-default", remote: true   %> 
						<%= link_to "Cancel", {controller: 'dashboard', action: 'index'}, class: "btn btn-md btn-default" %>
						<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-md btn-danger" %>
					</div>
</div>
</div>

app/views/panels/_fault.html.erb
 <div class="row">
    <div class="col-sm-7">
      <div class = "page-header"><h2>Fault Current Values</h2></div>
<%= link_to "View Panels", {controller: 'panels', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>
      <table class="table table-hover" id = "panel-table">
        <thead>
          <tr>
            <th>Panel Name</th>
            <th>F Value</th>
            <th>M Value</th>
            <th>Final Value</th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= panel.panel_name %></td>
            <td><%= number_with_precision(panel.f_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.m_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.final_value, precision: 2) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/panels/_form.html.erb
<%= form_for @panel, remote: true do |f| %>

<div class="container">


  <div class="row">
    <div class="col-sm-3">
  <div class="form-group">
    <%= f.label :panel_name %><br>
    <%= f.text_field :panel_name, :size => 35 %>
  </div>
  <div class="form-group">
    <%= f.label :wire_length %><br>
    <%= f.text_field :wire_length %>
  </div>
  <div class = "form-group" >
    <%= f.label :fed_from %><br>
    <%= f.select :fed_from, @panel_names %>
  </div>

  <div class="form-group">
    <%= f.label :runs %><br>
    <%= f.text_field :runs %>
  </div>
  <div class="form-group">
    <%= f.label :voltage %><br>
    <%= f.select :voltage, [208, 240, 480], {}, {class: "form-control"} %>
  </div>
    <div class="form-group">
    <%= f.label :wire_size %><br>
    <%= f.select :wire_size, ["14", "12", "10", "8", "6", "4", "3", "2", "1", 
      "1/0", "2/0", "3/0", "4/0", "250", "300", "350", "400", "500", "600", 
      "750", "1,000"], {}, {class: "form-control"} %>
  </div>
  </div>
</div>


    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
            <%= f.label :wire_type, "Copper", :value => 1 %><br>
           <%= f.radio_button :wire_type, 1,  {class: "form-control"} %>
            <%= f.label :wire_type, "Aluminum", :value => 2 %><br>
            <%= f.radio_button :wire_type, 2, {class: "form-control"} %>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="form-group">
            <%= f.label :conduit_type, "Magnetic", :value => 1 %><br>
           <%= f.radio_button :conduit_type, 1,  {class: "form-control"} %>
            <%= f.label :conduit_type, "Non-Magnetic", :value => 2 %><br>
            <%= f.radio_button :conduit_type, 2, {class: "form-control"} %>
      </div>
  </div>
      <div class="col-sm-3">
        <div class="form-group">
            <%= f.label :run_type, "Three Single Conductors", :value => 1 %><br>
           <%= f.radio_button :run_type, 1,  {class: "form-control"} %>
            <%= f.label :run_type, "Three Conductor Cable", :value => 2 %><br>
            <%= f.radio_button :run_type, 2, {class: "form-control"} %>
      </div>
  </div>
</div>



<div class = "row">
  <div class = "col-sm-3">
    <div class="form-group">
      <%= f.label :temp, "Wire Max Temperature" %><br>
     <%= f.select :temp, [60, 75, 90],  {class: "form-control"} %>
    </div>

  <div class="form-group">
    <%= f.label :conn_ampacity, "Connected Ampacity" %><br>
    <%= f.text_field :conn_ampacity %>
  </div>

  </div>
</div>



<div class="row">
  <div class="col-sm-3">
        <div class="form-group">
            <%= f.label :position %><br>
           <%= f.select :position, 1..@panel_count, {}, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @panel.project_id %>
          <%= f.button :Submit, name: "project_id", value: @panel.project_id, :class => 'btn btn-md btn-success'  %>       
          <%= link_to "Cancel", {controller: 'panels', action: 'index', project_id: @panel.project_id }, class: "btn btn-md btn-default", remote: true   %>
          <%= link_to 'Destroy', @panel, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-md btn-danger" %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/panels/_list.html.erb
<div class="container">
 </div>
<%= link_to "Back to Project", project_path(@project), class: "btn btn-md btn-default", remote: true %>
 <%= link_to "New Panel", {controller: 'panels', action: 'new', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
  <%= link_to "Fault Current", {controller: 'panels', action: 'fault', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
  <%= link_to "Voltage Drop", {controller: 'panels', action: 'voltdrop', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
 <div class="container">
  <div class="row">
    <div class="col-sm-11" id = "panel-table">
      <h2>Panel Values</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Panel Name</th>
            <th>Wire length</th>
            <th>Init fault</th>
            <th>Runs</th>
            <th>Voltage</th>
            <th>C value</th>
            <th>Wire Size</th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= link_to panel.panel_name, edit_panel_path(panel), class: "btn btn-md btn-default", remote: true %></td>
            <td><%= "#{panel.wire_length.to_i}'" %></td>
            <td><%= number_with_precision(panel.init_fault, precision: 2) %></td>
            <td><%= panel.runs.to_i %></td>
            <td><%= panel.voltage.to_i %></td>
            <td><%= panel.c_value.to_i %></td>
            <td><%= "##{panel.wire_size}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
      <% if !flash[:notice].blank? %>
    <div class="alert alert-danger fade in">
      <%= flash[:notice] %>
    </div>
    <% end %>
</div>

app/views/panels/_results.html.erb
 <div class="row">
    <div class="col-sm-7">
      <div class = "page-header"><h2>Fault Current Values</h2></div>
<%= link_to "View Panels", {controller: 'panels', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>
      <table class="table table-hover" id = "panel-table">
        <thead>
          <tr>
            <th>Panel Name</th>
            <th>F Value</th>
            <th>M Value</th>
            <th>Final Value</th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= panel.panel_name %></td>
            <td><%= number_with_precision(panel.f_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.m_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.final_value, precision: 2) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/panels/_voltdrop.html.erb
 <div class="row">
    <div class="col-sm-7">
      <div class = "page-header"><h2>Fault Current Values</h2></div>
<%= link_to "View Panels", {controller: 'panels', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>
      <table class="table table-hover" id = "panel-table">
        <thead>
          <tr>
            <th>Panel Name</th>
            <th>Wire Length</th>
            <th>Wire Size</th>
            <th>Voltage Loss</th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= panel.panel_name %></td>
            <td><%= panel.wire_length %></td>
            <td><%= "##{panel.wire_size} #{panel.wire_type == 0 ? "CU" : "AL"}" %></td>
            <td><%= "#{number_with_precision(panel.voltdrop, precision: 2)}%" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/panels/create.js.erb
$('#project-form').html("<%= j (render "list") %>");

app/views/panels/destroy.js.erb
$('#project-form').html("<%= j (render "list") %>");

app/views/panels/edit.js.erb
$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(600);

app/views/panels/fault.js.erb
$('#project-form').html("<%= j (render 'fault') %>");
$('#project-form').slideDown(600);

app/views/panels/new.js.erb
$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(600);

app/views/panels/show.js.erb
$('#project-form').html("<%= j (render 'list') %>");
$('#project-form').slideDown(600);

app/views/panels/update.js.erb
$('#project-form').html("<%= j (render "list") %>");

app/views/panels/voltdrop.js.erb
$(document).ready(function(){
	$('#project-form').html("<%= j (render 'voltdrop') %>");
	$('#project-form').slideDown(600);
});