config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  
  match '/users/logout', :to => 'users#logout', :via => [:get, :post]
  get '/logout' => 'session#destroy'
  match '/panels/fault', :to => 'panels#fault', :via => [:get, :post]
  match '/panels/voltdrop', :to => 'panels#voltdrop', :via => [:get, :post]
  match '/units/appliance', :to => 'units#appliance', :via => [:get, :post]
  match '/units/hvac', :to => 'units#hvac', :via => [:get, :post]
  match '/units/load', :to => 'units#load', :via => [:get, :post]
  match '/meterbanks/load', :to => 'meterbanks#load', :via => [:get, :post]
  resources :panels
  resources :users
  resources :projects
  resources :units
  resources :meterbanks

  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/unit.rb
class Unit < ActiveRecord::Base
belongs_to :project
before_save :set_small_app, :set_hvac, :set_lighting, :demand_load, :total

scope :sorted, lambda { order("units.sqr_ftg ASC")}

	def set_small_app
		self.small_app = ((((3 * self.sqr_ftg.to_i) / 120)/20)+1) * 1500	
	end

	def set_hvac
		self.hvac = self.heating + self.cooling + self.other_load
	end

	def set_lighting
		self.lighting = (self.sqr_ftg * 3) + self.small_app + self.washer
	end

	def total
		self.total_unit = self.demand + self.microwave + self.dishwasher +
		self.disposal + self.dryer + self.hvac
	end

	def demand_load
		self.demand = 3000 + ((self.lighting - 3000)* 0.35)
	end



end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  respond_to :js
  before_action :get_project
  before_action :index_project

	def index
		@units = Unit.where(:project_id => @project.id)
	end

	def new
	    @unit= Unit.new({:project_id => @project.id})
	end

	def create
		@units = Unit.where(:project_id => @project.id)
	    @unit = Unit.new(unit_params)
	    @unit.save
	end

  	def edit
  		@unit = Unit.find(params[:id])
  	end

  	def update
	    @units = Unit.where(:project_id => @project.id)
	  	@unit = Unit.find(params[:id])
	    @unit.update(unit_params)
  	end

  	def destroy
  	@unit = Unit.find(params[:id])
    @unit.destroy
	    respond_to do |format|
	      format.html { redirect_to '/dashboard/index', notice: "Unit: #{@unit.unit_name} was successfully destroyed" }
	      format.json { head :no_content }
	    end
  	end

  	def load
	  	@units = Unit.where(:project_id => @project.id)
  	end

  	def hvac
		@unit = Unit.find(params[:id])
  	end

  	def appliance
	  	@unit = Unit.find(params[:id])
  	end

  	def appupdate
	  	@unit = Unit.find(params[:id])
	  	@unit.update(unit_params)
  	end

  	def show
	  	@unit = Unit.find(params[:id])
  	end

	def unit_params
      params.require(:unit).permit(:unit_name, :unit_meter, :bedrooms, :sqr_ftg, :washer, :microwave,
      	:dishwasher, :disposal, :dryer, :voltage, :heating, :cooling, :other_load, :project_id)
   	end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_appform.html.erb
<%= form_for @unit, remote: true do |f| %>

<div class="container">
  <div class="row">
    <div class="col-sm-3">

  <div class="form-group">
    <%= f.label :washer %><br>
    <%= f.text_field :washer%>
  </div>

  <div class="form-group">
    <%= f.label :microwave %><br>
    <%= f.text_field :microwave%>
  </div>

  <div class = "form-group" >
    <%= f.label :dishwasher %><br>
    <%= f.text_field :dishwasher %>
  </div>

  <div class = "form-group" >
    <%= f.label :disposal %><br>
    <%= f.text_field :disposal %>
  </div>

  <div class = "form-group" >
    <%= f.label :dryer %><br>
    <%= f.text_field :dryer %>
  </div>


  </div>
</div>

<div class="row">
  <div class="col-sm-3">

        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @unit.project_id %>
          <%= f.button :Submit, name: "project_id", value: @unit.project_id, :class => 'btn btn-md btn-success'  %>       
          <%= link_to "Cancel", {controller: 'units', action: 'index', project_id: @unit.project_id }, class: "btn btn-md btn-default", remote: true   %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/units/_form.html.erb
<%= form_for @unit, remote: true do |f| %>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
  <div class="form-group">
    <%= f.label :unit_name %><br>
    <%= f.text_field :unit_name%>
  </div>
  <div class="form-group">
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms%>
  </div>
  <div class = "form-group" >
    <%= f.label :sqr_ftg %><br>
    <%= f.text_field :sqr_ftg%>
  </div>

  <div class="form-group">
    <%= f.label :voltage %><br>
    <%= f.select :voltage, [208, 240], {}, {class: "form-control"} %>
  </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">

        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @unit.project_id %>
          <%= f.button :Submit, name: "project_id", value: @unit.project_id, :class => 'btn btn-md btn-success'  %>       
          <%= link_to "Cancel", {controller: 'units', action: 'index', project_id: @unit.project_id }, class: "btn btn-md btn-default", remote: true   %>
          <%= link_to 'Destroy', @unit, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-md btn-danger" %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/units/_hvacform.html.erb
<%= form_for @unit, remote: true do |f| %>

<div class="container">
  <div class="row">
    <div class="col-sm-3">

  <div class="form-group">
    <%= f.label :heating %><br>
    <%= f.text_field :heating%>
  </div>

  <div class="form-group">
    <%= f.label :cooling %><br>
    <%= f.text_field :cooling%>
  </div>

  <div class = "form-group" >
    <%= f.label :other_load %><br>
    <%= f.text_field :other_load %>
  </div>


  </div>
</div>

<div class="row">
  <div class="col-sm-3">

        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @unit.project_id %>
          <%= f.button :Submit, name: "project_id", value: @unit.project_id, :class => 'btn btn-md btn-success'  %>       
          <%= link_to "Cancel", {controller: 'units', action: 'index', project_id: @unit.project_id }, class: "btn btn-md btn-default", remote: true   %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/units/_loadcalc.html.erb
 <div class="row">
    <div class="col-sm-7">
      <div class = "page-header"><h2>Unit Load Calculations</h2></div>
<%= link_to "View Units", {controller: 'units', action: 'index', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %> </p>
  
    <% @units.each do |unit| %>
    <div id = "unit-table">
      <h4><%= "Computed Load for Unit #{unit.unit_name}:" %></h4>

      <p>  <%= "Area of the largest dwelling unit is #{number_with_delimiter(number_with_precision(unit.sqr_ftg, precision: 0), :delimiter => ',')} sq ft." %><br /></p>
      <p> <b> General Lighing Load: </b><br />
           <%= "#{unit.sqr_ftg} sq ft. @ 3 Volt-Amperes per Square Foot = #{number_with_delimiter(number_with_precision(unit.sqr_ftg * 3, precision: 0), :delimiter => ',')} Volt-Amperes" %> <br />
           <%= "Small Appliance Load, (#{((((3 * unit.sqr_ftg.to_i) / 120)/20)+1)}) 20-Ampere Circuits = #{number_with_delimiter(unit.small_app, :delimiter => ',')} Volt-Amperes" %> <br /> 
           <%= "Washer = #{number_with_delimiter(unit.washer, :delimiter => ',')} Volt-Amperes" %> <br />
           <%= "Total Computed Load = #{number_with_delimiter(unit.lighting, :delimiter => ',')} Volt-Amperes" %> </p>

      <p>  <b>Application of Demand Factor: </b><br />
           <%= "3,000 Volt-Amperes @ 100% = #{unit.lighting > 3000 ? "3,000" : unit.lighting} Volt-Amperes" %><br />
           <%= "#{number_with_delimiter((unit.lighting - 3000) > 0 ? (unit.lighting - 3000) : 0, :delimiter => ',')} Volt-Amperes @ 35% = 
           #{number_with_delimiter(number_with_precision((unit.lighting - 3000) > 0 ? ((unit.lighting - 3000) * 0.35) : 0, precision: 0), :delimiter => ',')} Volt-Amperes" %><br />
           <%= "Net Computed Load = #{number_with_delimiter(unit.demand, :delimiter => ',')} Volt-Amperes" %></p>
      <p>   <%= "Microwave Load = #{number_with_delimiter(unit.microwave, :delimiter => ',')} Volt-Amperes" %><br />
            <%= "Dishwasher Load = #{number_with_delimiter(unit.dishwasher, :delimiter => ',')} Volt-Amperes" %><br />
            <%= "Disposer Load = #{number_with_delimiter(unit.disposal, :delimiter => ',')} Volt-Amperes" %><br />
            <%= "Clothes Dryer Load = #{number_with_delimiter(unit.dryer, :delimiter => ',')} Volt-Amperes" %><br />
            <%= "HVAC Load = #{number_with_delimiter(unit.hvac, :delimiter => ',')} Volt-Amperes" %></p>
      <p>   <%= "Net Computed Load for the Largest Dwelling Unit =" %> <b> <%= " #{number_with_delimiter(unit.total_unit, :delimiter => ',')} Volt-Amperes" %> </b><br />
            <%= "#{number_with_delimiter(unit.total_unit, :delimiter => ',')} / #{unit.voltage} Volts = " %> <b> <%= "#{number_with_precision((unit.total_unit.to_f / 208.to_f), precision: 0)} Amperes" %></b>
           <hr />
           <% end %>
    </div>
    </div>
  </div>

app/views/units/_unitlist.html.erb
<div class="container">
 </div>
<%= link_to "Back to Project", project_path(@project), class: "btn btn-md btn-default", remote: true %>
 <%= link_to "New Unit", {controller: 'units', action: 'new', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
  <%= link_to "Load Calculations", {controller: 'units', action: 'load', project_id: @project.id}, class: "btn btn-md btn-default", remote: true   %>
 <div class="container">
  <div class="row">
    <div class="col-sm-11" id = "unit-table">
      <h2>Unit Details</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Unit Name</th>
            <th>Bedrooms</th>
            <th>Square Footage</th>
            <th>Small Appliance Load</th>
            <th>Unit Voltage</th>
            <th>Major Appliances</th>
            <th>HVAC</th>
          </tr>
        </thead>

        <tbody>
          <% @units.each do |unit| %>
          <tr>
            <td><%= link_to unit.unit_name, edit_unit_path(unit), class: "btn btn-md btn-default", remote: true %></td>
            <td><%= unit.bedrooms %></td>
            <td><%= unit.sqr_ftg %></td>
            <td style = "width: 150px;"><%= "#{unit.small_app}W" %></td>
            <td><%= "#{unit.voltage}V" %></td>
            <td><%= link_to "Appliances", {controller: 'units', action: 'appliance', id: unit.id, project_id: @project.id}, class: "btn btn-md btn-default", remote: true %></td>
            <td><%= link_to "HVAC: #{unit.hvac}W", {controller: 'units', action: 'hvac', id: unit.id, project_id: @project.id}, class: "btn btn-md btn-default", remote: true %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
      <% if !flash[:notice].blank? %>
    <div class="alert alert-danger fade in">
      <%= flash[:notice] %>
    </div>
    <% end %>
</div>

app/views/units/appliance.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render "appform") %>");

});

app/views/units/create.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render "unitlist") %>");

});

app/views/units/hvac.js.erb
$(document).ready(function(){

$('#project-form').html("<%= j (render "hvacform") %>");

});

app/views/units/index.js.erb
$(document).ready(function(){
	$('.project-dash').hide();
	$('#project-form').html("<%= j (render 'unitlist') %>");
	$('#project-form').show();
});

app/views/units/update.js.erb
$(document).ready(function(){
$('#project-form').html("<%= j (render "unitlist") %>");
});